apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}:{{ .Values.imageTag }}
          imagePullPolicy: IfNotPresent
          ports:
            {{- range $index, $port := .Values.ports }}
            - containerPort: {{ $port }}
              name: port-{{ $index }}
            {{- end }}
          {{- if .Values.envFrom }}
          envFrom:
          {{- toYaml .Values.envFrom | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- range .Values.persistentVolumeClaims }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
            {{- if .Values.configMapMountPath }}
            - name: config-volume
              mountPath: {{ .Values.configMapMountPath }}
              readOnly: true
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
      volumes:
        {{- range .Values.persistentVolumeClaims }}
        {{- if .claimName }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .claimName }}
        {{- end }}
        {{- if .hostPath }}
        - name: {{ .name }}
          hostPath:
            path: {{ .hostPath }}
            type: Directory
        {{- end }}
        {{- end }}
        {{- if .Values.configMapMountPath }}
        - name: config-volume
          configMap:
            name: {{ .Chart.Name }}
        {{- end }}
