apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    {{- range $index, $port := .Values.ports }}
    - name: port-{{ $index }}
      protocol: TCP
      port: {{ $port }}
      targetPort: {{ $port }}
    {{- end }}