{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}